/**
 * Design System Configuration
 * 
 * This file is auto-generated by Coherent Design Method.
 * Do not edit manually - use 'coherent chat' command to modify.
 */

export const config = {
  "provider": "shadcn",
  "version": "1.0.0",
  "coherentVersion": "0.17.9",
  "frameworkVersions": {
    "next": "15.2.4",
    "react": "18.3.1",
    "tailwind": "3.4.17"
  },
  "name": "My App",
  "description": "Built with Coherent Design Method",
  "tokens": {
    "colors": {
      "light": {
        "primary": "#17a862",
        "secondary": "#4a5568",
        "accent": "#17a862",
        "success": "#17a862",
        "warning": "#b47a10",
        "error": "#d1383d",
        "info": "#4a5568",
        "background": "#fafaf7",
        "foreground": "#0a0a0a",
        "muted": "#f4f3ef",
        "border": "#e7e6e0"
      },
      "dark": {
        "primary": "#3ecf8e",
        "secondary": "#a1a1a1",
        "accent": "#3ecf8e",
        "success": "#3ecf8e",
        "warning": "#f5a623",
        "error": "#ff5c5c",
        "info": "#61afef",
        "background": "#0a0a0a",
        "foreground": "#ededed",
        "muted": "#161616",
        "border": "#1f1f1f"
      }
    },
    "spacing": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem",
      "xl": "2rem",
      "2xl": "3rem",
      "3xl": "4rem"
    },
    "typography": {
      "fontFamily": {
        "sans": "Inter, system-ui, sans-serif",
        "mono": "JetBrains Mono, monospace"
      },
      "fontSize": {
        "xs": "0.75rem",
        "sm": "0.875rem",
        "base": "1rem",
        "lg": "1.125rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem"
      },
      "fontWeight": {
        "normal": 400,
        "medium": 500,
        "semibold": 600,
        "bold": 700
      },
      "lineHeight": {
        "tight": 1.25,
        "normal": 1.5,
        "relaxed": 1.75
      }
    },
    "radius": {
      "none": "0",
      "sm": "0.25rem",
      "md": "0.5rem",
      "lg": "0.75rem",
      "xl": "1rem",
      "full": "9999px"
    }
  },
  "theme": {
    "defaultMode": "dark",
    "allowModeToggle": true
  },
  "components": [
    {
      "id": "button",
      "name": "Button",
      "category": "form",
      "source": "custom",
      "baseClassName": "inline-flex items-center justify-center rounded-md font-medium transition-colors",
      "variants": [
        {
          "name": "default",
          "className": "bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
        },
        {
          "name": "secondary",
          "className": "bg-secondary text-secondary-foreground hover:bg-secondary/80 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
        },
        {
          "name": "outline",
          "className": "border border-input bg-background hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
        },
        {
          "name": "destructive",
          "className": "bg-destructive text-destructive-foreground hover:bg-destructive/90 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
        }
      ],
      "sizes": [
        {
          "name": "sm",
          "className": "h-8 px-3 text-xs"
        },
        {
          "name": "md",
          "className": "h-9 px-4 text-sm"
        },
        {
          "name": "lg",
          "className": "h-10 px-6 text-base"
        }
      ],
      "usedInPages": [],
      "createdAt": "2026-03-08T07:26:36.623Z",
      "updatedAt": "2026-03-08T07:26:36.623Z"
    },
    {
      "id": "card",
      "name": "Card",
      "category": "data-display",
      "source": "custom",
      "baseClassName": "rounded-lg border bg-card text-card-foreground shadow-sm",
      "variants": [],
      "sizes": [],
      "usedInPages": [],
      "createdAt": "2026-03-08T07:26:36.623Z",
      "updatedAt": "2026-03-08T07:26:36.623Z"
    },
    {
      "id": "switch",
      "name": "Switch",
      "category": "form",
      "source": "custom",
      "baseClassName": "",
      "variants": [],
      "sizes": [],
      "usedInPages": [],
      "createdAt": "2026-03-08T07:26:36.623Z",
      "updatedAt": "2026-03-08T07:26:36.623Z"
    },
    {
      "id": "badge",
      "name": "Badge",
      "category": "data-display",
      "source": "shadcn",
      "shadcnComponent": "badge",
      "baseClassName": "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold",
      "variants": [
        {
          "name": "default",
          "className": "border-transparent bg-primary text-primary-foreground"
        },
        {
          "name": "secondary",
          "className": "border-transparent bg-secondary text-secondary-foreground"
        },
        {
          "name": "success",
          "className": "border-transparent bg-success text-white"
        },
        {
          "name": "error",
          "className": "border-transparent bg-error text-white"
        },
        {
          "name": "outline",
          "className": "text-foreground"
        }
      ],
      "sizes": [
        {
          "name": "sm",
          "className": "text-xs px-2 py-0.5"
        },
        {
          "name": "md",
          "className": "text-sm px-2.5 py-0.5"
        },
        {
          "name": "lg",
          "className": "text-base px-3 py-1"
        }
      ],
      "usedInPages": [],
      "createdAt": "2026-03-08T07:30:28.242Z",
      "updatedAt": "2026-03-08T07:30:28.242Z"
    },
    {
      "id": "avatar",
      "name": "Avatar",
      "category": "data-display",
      "source": "custom",
      "baseClassName": "relative flex shrink-0 overflow-hidden rounded-full bg-muted",
      "variants": [],
      "sizes": [
        {
          "name": "xs",
          "className": "size-6 text-xs"
        },
        {
          "name": "sm",
          "className": "size-8 text-xs"
        },
        {
          "name": "md",
          "className": "size-10 text-sm"
        },
        {
          "name": "lg",
          "className": "size-12 text-base"
        },
        {
          "name": "xl",
          "className": "size-14 text-lg"
        }
      ],
      "usedInPages": [],
      "createdAt": "2026-04-29T00:00:00.000Z",
      "updatedAt": "2026-04-29T00:00:00.000Z"
    },
    {
      "id": "input",
      "name": "Input",
      "category": "form",
      "source": "custom",
      "baseClassName": "flex w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
      "variants": [],
      "sizes": [
        {
          "name": "sm",
          "className": "h-8 text-xs"
        },
        {
          "name": "md",
          "className": "h-9 text-sm"
        },
        {
          "name": "lg",
          "className": "h-10 text-base"
        }
      ],
      "usedInPages": [],
      "createdAt": "2026-04-29T00:00:00.000Z",
      "updatedAt": "2026-04-29T00:00:00.000Z"
    },
    {
      "id": "label",
      "name": "Label",
      "category": "form",
      "source": "custom",
      "baseClassName": "text-sm font-medium leading-none text-foreground",
      "variants": [],
      "sizes": [],
      "usedInPages": [],
      "createdAt": "2026-04-29T00:00:00.000Z",
      "updatedAt": "2026-04-29T00:00:00.000Z"
    },
    {
      "id": "alert",
      "name": "Alert",
      "category": "feedback",
      "source": "custom",
      "baseClassName": "relative w-full rounded-lg border px-4 py-3 text-sm",
      "variants": [
        {
          "name": "default",
          "className": "bg-background text-foreground border-border"
        },
        {
          "name": "destructive",
          "className": "border-destructive/50 text-destructive"
        },
        {
          "name": "success",
          "className": "border-success/50 text-success"
        },
        {
          "name": "warning",
          "className": "border-warning/50 text-warning"
        }
      ],
      "sizes": [],
      "usedInPages": [],
      "createdAt": "2026-04-29T00:00:00.000Z",
      "updatedAt": "2026-04-29T00:00:00.000Z"
    },
    {
      "id": "skeleton",
      "name": "Skeleton",
      "category": "feedback",
      "source": "custom",
      "baseClassName": "animate-pulse rounded-md bg-muted",
      "variants": [],
      "sizes": [],
      "usedInPages": [],
      "createdAt": "2026-04-29T00:00:00.000Z",
      "updatedAt": "2026-04-29T00:00:00.000Z"
    },
    {
      "id": "progress",
      "name": "Progress",
      "category": "feedback",
      "source": "custom",
      "baseClassName": "relative h-2 w-full overflow-hidden rounded-full bg-muted",
      "variants": [],
      "sizes": [],
      "usedInPages": [],
      "createdAt": "2026-04-29T00:00:00.000Z",
      "updatedAt": "2026-04-29T00:00:00.000Z"
    }
  ],
  "layoutBlocks": [],
  "pages": [
    {
      "id": "home",
      "name": "Home",
      "route": "/",
      "layout": "centered",
      "sections": [],
      "generatedWithPageCode": true,
      "pageAnalysis": {
        "sections": [
          {
            "name": "Hero",
            "order": 0
          },
          {
            "name": "The Problem",
            "order": 1
          },
          {
            "name": "Two Ways to Build",
            "order": 2
          },
          {
            "name": "What Makes It Different",
            "order": 3
          },
          {
            "name": "Getting Started",
            "order": 4
          },
          {
            "name": "Footer",
            "order": 5
          }
        ],
        "componentUsage": {},
        "iconCount": 12,
        "layoutPattern": "unknown",
        "hasForm": false,
        "analyzedAt": "2026-03-10T03:15:58.204Z"
      },
      "title": "Home",
      "description": "Home page",
      "requiresAuth": false,
      "noIndex": false,
      "createdAt": "2026-03-09T14:49:48.031Z",
      "updatedAt": "2026-03-10T03:15:58.204Z"
    }
  ],
  "navigation": {
    "enabled": true,
    "type": "header",
    "items": [
      {
        "label": "Home",
        "route": "/",
        "requiresAuth": false,
        "order": 1
      }
    ]
  },
  "features": {
    "authentication": {
      "enabled": false,
      "strategies": []
    },
    "payments": {
      "enabled": false
    },
    "analytics": {
      "enabled": false
    },
    "database": {
      "enabled": false
    },
    "stateManagement": {
      "enabled": false,
      "provider": "zustand"
    }
  },
  "settings": {
    "initialized": true,
    "appType": "multi-page",
    "framework": "next",
    "typescript": true,
    "cssFramework": "tailwind",
    "autoScaffold": true,
    "homePagePlaceholder": false
  },
  "createdAt": "2026-03-08T07:26:36.623Z",
  "updatedAt": "2026-03-10T03:15:58.205Z"
} as const
